[theme]
primaryColor="#120caf"
backgroundColor="#dee6f3"
secondaryBackgroundColor="#4a62ce"
textColor="#000000"

[server]
headless = true
port = 10000

[browser]
serverAddress = "0.0.0.0"
serverPort = 10000


